### ISSUE TITLE
Use with component state instead of the store?

### ISSUE THREAD

**Issue by markerikson** [jasonslyvia/redux-form-utils#1]
This looks sorta kinda like something I threw together while prototyping stuff recently.  I wanted to have controlled inputs in a form, with immediate updates as the user typed, but only dispatch events on a delay after the user paused typing to cut down on the total number of "STUFF_EDITED" events that went through.  The component I came up with is over here: https://gist.github.com/markerikson/554cab15d83fd994dfab

Your utility looks passably similar to what I did, but more in depth.  I see that the wrapper component you generate does takes "dispatch" as an optional prop.  Would it be possible to use it in such a way that the "dispatched" actions actually get handled by a parent component rather than going straight to the Redux store?

**Comment by jasonslyvia** [comment]
It's kind of a trade-off, you choose between a fully controlled store or a easy-to-code-but-harder-to-reason state(even you can just use `refs` for form controls to get its value).

I prefer the former one personally, despite its verbosity, it is really helpful when you're reasoning about your app, or for example, initializing with default value.

**Comment by jasonslyvia** [comment]
I'm closing this issue, if you have further concerns, feel free to reopen it.
